import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import ConditionLayout from "@/components/ConditionalLayout";
import Script from "next/script";
import { AppProvider } from "@/context/AppContext";
import { BuyNowProvider } from "@/context/BuyNowContext";
//import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>  
      <Script 
          src="https://checkout.razorpay.com/v1/checkout.js" 
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
        <CartProvider>
        <WishlistProvider>
          

          <ConditionLayout>{children}</ConditionLayout>
          </WishlistProvider>
        </CartProvider>
        </AppProvider>
       
      </body>
    </html>
  );
}